// @ts-ignore
import { serve } from "https://deno.land/std@0.168.0/http/server.ts"

// Declare Deno global for IDE type-checking outside of Deno runtime env
declare const Deno: {
  env: {
    get(key: string): string | undefined
  }
}

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
}

serve(async (req: Request) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const apiKey = Deno.env.get("GEMINI_API_KEY")
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY is not configured in the environment")
    }

    const { mode, topic, subtopic, difficulty, messages } = await req.json()

    if (mode === 'practice') {
      if (!topic || !subtopic || !difficulty) {
        return new Response(
          JSON.stringify({ error: "Missing required fields (topic, subtopic, difficulty) for practice mode" }),
          { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        )
      }

      // Generate quiz question using Gemini with structured JSON Schema
      const systemPrompt = "You are a CS teaching assistant for a B.Tech AI/ML student. Given a topic, subtopic, and difficulty level, generate ONE practice question with a full explanation. Respond with ONLY valid JSON, no markdown fences, no preamble, matching this exact schema: { topic, subtopic, difficulty (easy|medium|hard), question_type (mcq|short_answer|code_trace), question, options (array, only for mcq), correct_answer, explanation (3-6 sentences, teaches the reasoning), common_mistake (one likely wrong reasoning path) }. For code_trace questions, embed a short code snippet inside question using \\n for line breaks. Keep difficulty honest: hard requires multi-step reasoning, not just harder vocabulary."

      const userPrompt = `Topic: ${topic}\nSubtopic: ${subtopic}\nDifficulty: ${difficulty}`

      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent?key=${apiKey}`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            contents: [
              {
                role: "user",
                parts: [{ text: userPrompt }]
              }
            ],
            systemInstruction: {
              parts: [{ text: systemPrompt }]
            },
            generationConfig: {
              responseMimeType: "application/json",
              responseSchema: {
                type: "OBJECT",
                properties: {
                  topic: { type: "STRING" },
                  subtopic: { type: "STRING" },
                  difficulty: { type: "STRING", enum: ["easy", "medium", "hard"] },
                  question_type: { type: "STRING", enum: ["mcq", "short_answer", "code_trace"] },
                  question: { type: "STRING" },
                  options: {
                    type: "ARRAY",
                    items: { type: "STRING" }
                  },
                  correct_answer: { type: "STRING" },
                  explanation: { type: "STRING" },
                  common_mistake: { type: "STRING" }
                },
                required: ["topic", "subtopic", "difficulty", "question_type", "question", "options", "correct_answer", "explanation", "common_mistake"]
              }
            }
          })
        }
      )

      if (!response.ok) {
        const errorText = await response.text()
        console.error("Gemini API error:", errorText)
        throw new Error(`Gemini API returned error: ${response.status} ${response.statusText}`)
      }

      const responseData = await response.json()
      const text = responseData.candidates?.[0]?.content?.parts?.[0]?.text
      if (!text) {
        throw new Error("No content generated by Gemini")
      }

      // Return the generated question JSON directly
      return new Response(text, {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })

    } else if (mode === 'explain') {
      if (!messages || !Array.isArray(messages)) {
        return new Response(
          JSON.stringify({ error: "Missing or invalid messages array for explain mode" }),
          { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        )
      }

      // Map chat messages format to Gemini contents format
      // messages input format: [{ role: 'user' | 'model', content: 'string' }]
      const contents = messages.map(msg => ({
        role: msg.role === 'assistant' ? 'model' : 'user',
        parts: [{ text: msg.content }]
      }))

      const systemPrompt = "You are a patient CS tutor. Explain clearly and step by step, using small concrete examples. Keep responses under ~200 words unless asked for more depth."

      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent?key=${apiKey}`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            contents: contents,
            systemInstruction: {
              parts: [{ text: systemPrompt }]
            }
          })
        }
      )

      if (!response.ok) {
        const errorText = await response.text()
        console.error("Gemini API error:", errorText)
        throw new Error(`Gemini API returned error: ${response.status} ${response.statusText}`)
      }

      const responseData = await response.json()
      const text = responseData.candidates?.[0]?.content?.parts?.[0]?.text
      if (!text) {
        throw new Error("No explanation generated by Gemini")
      }

      return new Response(JSON.stringify({ response: text }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })

    } else {
      return new Response(
        JSON.stringify({ error: "Invalid mode. Must be 'practice' or 'explain'" }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

  } catch (error: any) {
    console.error("Serverless function error:", error)
    return new Response(
      JSON.stringify({ error: error?.message || "An unexpected error occurred" }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})

